### ISSUE TITLE
Problem with videos from youtube

### ISSUE THREAD

**Issue by HACKHERS** [Web-Feet/coastercms#23]
Hello, I tried to add video to page but now I cant even edit page back.

I have seen the api keys in settings page, when I first did this they are blank but then I update them from:console.developers.google.com when I tried that again still same. 

When I go to updated page it says: Video does not exist, it may have been removed from youtube

`ErrorException in a443fb6d45f634e921228ba3960637ad385cd3f7.php line 6:
Call to undefined method CoasterCms\Libraries\Blocks\Video::dl() (View: D:\work7\htdocs\sarpaykent\vendor\web-feet\coasterframework\resources\views\admin\blocks\video\main.blade.php)`

`FatalThrowableError in a443fb6d45f634e921228ba3960637ad385cd3f7.php line 6:
Call to undefined method CoasterCms\Libraries\Blocks\Video::dl()`

**Comment by neil-jennings** [comment]
Hi Hackhers,

There are default API keys in the config files in coaster which are used if the settings fields are blank:
https://github.com/Web-Feet/coasterframework/blob/master/config/key.php

With regards to the view issue it should be fixed from v5.3.21 of the coasterframework (duplicate issue of #18 ).

**Comment by HACKHERS** [comment]
Hi Neil,

I just updated the composer and keys with defaults, It works now but It still says: Video does not exist, it may have been removed from youtube

and I know its different thing but I want to ask that why I'm getting this error: https://i.imgur.com/aPp8w61.png

**Comment by neil-jennings** [comment]
We've come across this issue before with Windows, it's something to do with the local ssl certificates.

Have a look at:
http://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate#answer-34883260

**Comment by HACKHERS** [comment]
Thank you, I'm not sure you noticed the problem still exists with "Video does not exist, it may have been removed from youtube". 

Note: It shows in frontend

**Comment by neil-jennings** [comment]
There is likely an issue with the youtube server key the front end uses. Either check you own key or use the default one as it has no restrictions on it and it's not reached any limit (just tested locally and it's working).

**Comment by HACKHERS** [comment]
Strange, yesterday It's not working but now its working.

Thank you,
