### ISSUE TITLE
Array to string conversion error in video/main.blade.php

### ISSUE THREAD

**Issue by Dannymx** [Web-Feet/coastercms#54]
When saving a field that has a video, I'm getting an error at line 18 in `/vendor/web-feet/coasterframework/resources/views/admin/blocks/video/main.blade.php`

I var_dump'd the $content and includes a 'exists' and 'selected' keys with some values.

**Comment by SarajevoNo1** [comment]
You have issue (bug) in new theme 2017 in some templates, like internal, blog etc... When editing or adding new template, create content and add or update we get this message (picture in attachment).

![error video php](https://user-images.githubusercontent.com/28009477/28249334-24f0d75c-6a54-11e7-9cb9-cc68a23d77b2.jpg)
![error video php](https://user-images.githubusercontent.com/28009477/28249340-2fa3284e-6a54-11e7-92e1-cb08eecc5806.jpg)

**Comment by neil-jennings** [comment]
Should both be fixed as of v5.4.17

**Comment by SarajevoNo1** [comment]
Hi Neil please can you answer me on our last conversation about implementing lang switcher...

I sent u in last email that we added everything like u said in main menu.. Middleware..Kernel...and Chardwich than says to add these two line in routes/web.php...but it still not working..qont change content to other lang..

juli.croatiago.com

Thanks very much

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
